### PR TITLE
Adding a template for segmented large MNL models

### PR DESCRIPTION
**Pull request by smmaurer**
This PR adds a template for segmented large MNL models. 

The template automatically generates a set of submodels corresponding to categories of choosers. The user can edit the submodels as needed.

- Here's the code: [segmented_large_multinomial_logit.py](https://github.com/UDST/urbansim_templates/blob/0535d9a7d5b6c9a699105a1a87d9eda462615d83/urbansim_templates/models/segmented_large_multinomial_logit.py)
- Here's a demo using fake testing data: [2018-09-segmented-models.ipynb](https://github.com/UDST/public-template-workspace/blob/58945132800607446e7b6eb6cf00dbd47659d32b/notebooks-sam/2018-09-segmented-models.ipynb)

### Usage

`SegmentedLargeMultinomialLogitStep` takes the following inputs:
1. a `defaults` object, which is a `LargeMultinomialLogitStep` containing initial parameter values for the submodels
2. a `segmentation_column`, the name of a column of categorical values in the choosers table
3. `name` and `tags`, like all templates

```py
m = SegmentedLargeMultinomialLogitStep()
m.defaults.choosers = ...
m.defaults.alternatives = ...
m.defaults.choice_column = ...
m.defaults.model_expression = ...
m.segmentation_column = ...

m.build_submodels()

m.submodels ...  # edit submodels as needed

m.fit_all()
```

#### Editing submodels:

`m.submodels` is a dict of `LargeMultinomialLogitSteps`, identified by category name. You can edit their properties as needed, fit them individually, etc.

After the submodels are created, you can update a property for all of them at once by updating it in the `m.defaults` object. (Customizations to other properties will remain intact.)

### Discussion

The submodels are generated using `chooser_filters`, which are applied on top of any manually specified filters.

There's a full suite of unit tests here: [test_segmented_large_multinomial_logit.py](https://github.com/UDST/urbansim_templates/blob/0535d9a7d5b6c9a699105a1a87d9eda462615d83/urbansim_templates/tests/test_segmented_large_multinomial_logit.py)

Choice simulation will not be implemented in this PR.

### Versioning

- updates library version to 0.1.dev14

### CODE REVIEW

**Comment by smmaurer** [comment]
@mxndrwgrdnr How does this look?

**Comment by smmaurer** [comment]
@mxndrwgrdnr Save/reload should work now! The yaml file stores the submodels in a dictionary.

**Comment by mxndrwgrdnr** [comment]
💯

**Comment by smmaurer** [comment]
@mxndrwgrdnr Finished with testing; I'm going to merge this PR into the master branch.

**Pull request merged**
